-- database/migration/proposed-reference-additions.sql
-- Vocabulary the legacy tutor data uses that the v3 seed files do not cover.
-- GENERATED by propose-reference-additions.js — review every line before running.
-- Threshold: strings appearing in >= 2 legacy records.

START TRANSACTION;

-- ── Delhi localities ─────────────────────────────────────────────
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Rajdhani Enclave', 'rajdhani-enclave', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 14 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'MP Enclave', 'mp-enclave', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 7 tutors, spelt "mp enclave" in the export
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Nehru Vihar', 'nehru-vihar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 6 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Kanhaiya Nagar', 'kanhaiya-nagar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 6 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Indra Vihar', 'indra-vihar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 5 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Multani Mohalla', 'multani-mohalla', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 5 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Sharda Niketan', 'sharda-niketan', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 5 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Chander Lok', 'chander-lok', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 4 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Nimri Colony', 'nimri-colony', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 4 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Kalyan Vihar', 'kalyan-vihar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 4 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Meera Bagh', 'meera-bagh', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 4 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Baljeet Nagar', 'baljeet-nagar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
-- skipped "rajdhani" (3 tutors) — duplicate of another entry
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Shivaji Park', 'shivaji-park', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Vasudha Enclave', 'vasudha-enclave', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Polstar', 'polstar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Rajinder Nagar', 'rajinder-nagar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Sagarpur', 'sagarpur', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Lajwanti', 'lajwanti', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Gopalpur', 'gopalpur', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Roshnara Road', 'roshnara-road', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Jhandewalan', 'jhandewalan', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- skipped "chanderlok" (2 tutors) — duplicate of another entry
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Yojna Vihar', 'yojna-vihar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors, spelt "yojnavihar" in the export
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Chander Nagar', 'chander-nagar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors, spelt "chandar nagar" in the export
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Shree Nagar', 'shree-nagar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Samrat Enclave', 'samrat-enclave', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors, spelt "smarat enclave" in the export
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Roop Nagar', 'roop-nagar', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Shiva Market', 'shiva-market', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Raja Garden', 'raja-garden', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Pooth Kalan', 'pooth-kalan', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Rohit Kunj', 'rohit-kunj', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
INSERT INTO locations (name, slug, location_type, parent_location_id) SELECT 'Mahendru Enclave', 'mahendru-enclave', 'locality', id FROM locations WHERE slug = 'delhi-city' ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors

-- ── Subjects ─────────────────────────────────────────────────────
-- Only add the ones that are genuinely school subjects; the rest should
-- stay in tutor_custom_subjects for admin review.
-- INSERT INTO subjects (name, slug) VALUES ('Sociology', 'sociology') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 10 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Economic', 'economic') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 5 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Reasoning', 'reasoning') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 5 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Punjabi', 'punjabi') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 5 tutors
-- INSERT INTO subjects (name, slug) VALUES ('B.st', 'b-st') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Xii', 'xii') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Arts', 'arts') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 3 tutors
-- INSERT INTO subjects (name, slug) VALUES ('#039', '039') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('All Subjects Upto 10th', 'all-subjects-upto-10th') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Java', 'java') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Ved Path In Dav', 'ved-path-in-dav') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Taxation', 'taxation') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Law', 'law') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Legal Studies', 'legal-studies') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Any Subject', 'any-subject') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('All Subjects Upto 8th', 'all-subjects-upto-8th') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Financial Management', 'financial-management') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('All Subjects Upto 7th', 'all-subjects-upto-7th') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Quantitative Aptitude', 'quantitative-aptitude') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Pcm', 'pcm') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('All Subjects Upto 10', 'all-subjects-upto-10') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Any Subject 1st To 5th', 'any-subject-1st-to-5th') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('General Knowledge', 'general-knowledge') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('Grammar', 'grammar') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('E.v.s', 'e-v-s') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('G.k', 'g-k') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors
-- INSERT INTO subjects (name, slug) VALUES ('S.s.t', 's-s-t') ON DUPLICATE KEY UPDATE is_active = TRUE;  -- 2 tutors

COMMIT;